### ISSUE TITLE
use row and col names for kinship matrix

### ISSUE THREAD

**Issue by timflutre** [germmtz/gemma--VS--mm4lmm#1]
The current code doesn't work with the latest version of rutilstimflutre. This is because the gemma function now checks the names of the kinship matrix (K.c) with the row names of the SNP genotype matrix (X).
The kinship matrix saved in "Kinship.RData" should have row and col names.

**Comment by germmtz** [comment]
I just added row and col names to the kinship matrix and checked that the code run correctly. Everything seems to work out.
